packages:
  - examples/simple-example
  - examples/advanced-example
  - examples/collections-example
  - examples/conditional-rules-example
  - examples/custom-rules-example
  - examples/required-indicators-example
  - examples/server-validation-example
